/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task2.prac2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        XmlReader reader = new XmlReader();
        Document document = reader.readXmlFile("data.xml");
        // do something with the document object

    }
}
